version: '3.8'

services:
  web:
    image: bank
    build: . #this will build from current dir if banking image is not on your system
    volumes:
      - .:/app
    ports:
      - "8001:8000" # Internal 8000 to external 8001
    env_file:
      - .env
    depends_on:
      - db
    restart: "no"

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env

volumes:
  postgres_data:
