version: '3.8'

services:
  web:
    build: .
    volumes:
      - .:/app
    ports:
      - "8001:8000" # Internal 8000 to external 8001
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env

volumes:
  postgres_data:
