apiVersion: apps/v1
kind: Deployment
metadata:
  name: banking-app-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: banking-app-db
  template:
    metadata:
      labels:
        app: banking-app-db
    spec:
      containers:
      - name: postgres
        image: postgres:13
        ports:
        - containerPort: 5432
        envFrom:
        - configMapRef:
            name: lightbulb-config
        volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: postgres-storage
        persistentVolumeClaim:
          claimName: postgres-pvc
