apiVersion: apps/v1
kind: Deployment
metadata:
  name: banking-app-nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: banking-app-nginx
  template:
    metadata:
      labels:
        app: banking-app-nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.25
        ports:
        - containerPort: 80
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/conf.d/default.conf
          subPath: nginx.conf
      volumes:
      - name: nginx-config
        configMap:
          name: nginx-config
